### PR TITLE
Benefits Page Review

### PR DESCRIPTION
**Pull request by ghost**
Added a new image to the header. Also fixed some sentences for better readability.

### CODE REVIEW

**Review by AmericoChiclana — CHANGES_REQUESTED** [review]
.

**Review by AmericoChiclana — CHANGES_REQUESTED** [review]
also this one to dev

**Comment by ghost** [comment]
> 

There is no difference between creating a new branch and dev branch. Both can be checked and then pushed to main. :)

**Review by thijs-franck — APPROVED** [review]
Looks good, thanks

**Pull request merged**
